-- liquibase formatted sql

-- changeset kasia:1
CREATE TABLE producer (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(255) NOT NULL UNIQUE
);

-- changeset kasia:2
CREATE TABLE product (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         producer_id BIGINT NOT NULL,
                         name VARCHAR(255) NOT NULL,
                         description TEXT,
                         price DECIMAL(10, 2) NOT NULL,
                         attributes JSON,
                         CONSTRAINT fk_product_producer FOREIGN KEY (producer_id) REFERENCES producer(id)
);

-- changeset kasia:3
-- test data
INSERT INTO producer (name) VALUES ('Samsung'), ('Apple'), ('Dell'), ('Sony');